name: check_vars

on:
  schedule:
    # - cron: '0 18 * * *'
    - cron: '*/5 * * * *'
  push:
    paths:
      - '**.py'
      - '.github/workflows/check-vars.yml'
      - 'vars.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          vars.yml
          updateVars.py
          requirements.txt
          build-httpd.yml
        sparse-checkout-cone-mode: false
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run updateVars.py
      run: python updateVars.py
    
    - name: Check if vars.yml has changed
      run: |
        if git diff --quiet vars.yml; then
          echo "No changes in vars.yml"
          echo "false" > vars_changed.txt
        else
          echo "Changes detected in vars.yml"
          echo "true" > vars_changed.txt
        fi

    - name: Upload vars_changed as artifact
      uses: actions/upload-artifact@v3
      with:
        name: vars_changed
        path: vars_changed.txt

    - name: Commit and Push vars.yml if it has changed
      run: |
        if [[ $(cat vars_changed.txt) == 'true' ]]; then
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add vars.yml
          git commit -m "Auto-update vars.yml"
          git push
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
