name: Check if vars.yml is up-to-date

on:
  schedule:
    - cron: '0 18 * * *'
  push:
    paths:
      - '**.py'
      - '.github/workflows/check-vars.yml'
      # - 'vars.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@latest
      with:
        fetch-depth: 0  # this is required to get the full history and be able to push
    
    - name: Cache dependencies
      uses: actions/cache@v3.3.2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v4.7.1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run updateVars.py
      run: python updateVars.py
    
    - name: Check if vars.yml has changed
      id: check_changes
      run: |
        if git diff --quiet vars.yml; then
          echo "No changes in vars.yml"
          echo "::set-output name=changed::false"
        else
          echo "Changes detected in vars.yml"
          echo "::set-output name=changed::true"
        fi

    - name: Commit and Push vars.yml if it has changed
      if: steps.check_changes.outputs.changed == 'true'
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add vars.yml
        git commit -m "Update vars.yml"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
