name: Update vars.yml file

on:
  schedule:
    - cron: '0 18 * * *'
  push:
    paths:
      - '**.py'
#       - '.github/workflows/update-vars.yml'
      - 'vars.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # this is required to get the full history and be able to push
    
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run updateVars.py
      run: python updateVars.py

    - name: Commit and push if vars.yml is modified
      run: |
        git diff --exit-code || exit 0  # Exit if there are no changes
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git commit -am "Update vars.yml" || exit 0
        git push
